name: Healthcheck

on:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  curl:
    name: Calling App Healthcheck Endpoint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [18.x]
        os: [ubuntu-latest]
    
    steps:
      - name: cURL
        uses: wei/curl@v1
        with:
          args: -X GET ${{ secrets.APP_URL }}